#!/bin/bash
# ~/.bash_aliases: automatically executed by ~/.bashrc

# Kubernetes

## kubectl
alias k=kubectl
complete -F __start_kubectl k

## get/set namespace
k_ns() {
  if [ -z "${1}" ]; then
    kubectl config view --minify --output 'jsonpath={..namespace}'; echo
  else
    kubectl config set-context --current --namespace="${1}"
  fi
}
alias kns=k_ns

# Podman
prun() {
  local podman_image=${1}
  shift

  declare podman_args=()
  while [ -n "${1}" ] && [ "${1}" != "--" ]; do
    podman_args+=("${1}")
    shift
  done

  if [ "${1}" = "--" ]; then
    shift
  fi

  podman run --rm -it \
    "${podman_args[@]}" \
    "${podman_image}" \
    "$@"
}

prun_workspace() {
  local podman_image=${1}
  shift

  prun "${podman_image}" --volume "$(pwd):/workspace" --workdir /workspace "$@"
}

export -f prun
export -f prun_workspace

alias p=podman

# Java
jdk() {
  local java_version=${1}
  shift

  prun "docker.io/library/eclipse-temurin:${java_version}" "$@"
}

j17() {
  jdk 17 "$@"
}

j() {
  j17 "$@"
}

export -f j17
export -f j

# Maven
maven() {
  local maven_jdk_version=${1}
  shift

  prun_workspace "docker.io/library/maven:3-eclipse-temurin-${maven_jdk_version}" --volume ~/.m2:/root/.m2 -- mvn "$@"
}

mvn8() {
  maven 8 "$@"
}
mvn11() {
  maven 11 "$@"
}
mvn17() {
  maven 17 "$@"
}
mvn21() {
  maven 21 "$@"
}
mvn24() {
  maven 24 "$@"
}
mvn25() {
  maven 25 "$@"
}
mvn() {
  mvn24 "$@"
}

export -f mvn8
export -f mvn11
export -f mvn17
export -f mvn21
export -f mvn24
export -f mvn25
export -f mvn

# Bat
alias cat='batcat'
